language: ruby
cache: bundler
sudo: false
rvm: 2.2
dist: trusty

install: script/bootstrap
script: script/cibuild

jobs:
  include:
    - script: echo "Running unit tests (1)"
    - script: echo "Running unit tests (2)"
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true