language: ruby
cache: bundler
sudo: false
rvm: 2.2
dist: trusty

jobs:
  include:
    - script:
        script/bootstrap
    	script/cibuild
    - stage: GitHub Release
      script: skip
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH_TOKEN"
        skip_cleanup: true
        on:
          tags: true