title = "computational.life"
baseURL = "https://computational.life/"
languageCode = "en-us"
theme = "ananke"
publishDir = ""

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "UA-100347549-3"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  AuthorName = "Kyle Harrington"
  favicon = ""
  site_logo = ""
  description = "computational.life"
  facebook = ""
  twitter = "https://twitter.com/kisharrington"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sciview-hero-image.jpg"
  recent_posts_number = 2

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "The about section"
    url = "/about/"
    weight = -110

# https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true